version: '3.9'
services:

  postgres:
    container_name: auth-db
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - sso-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sso-network:
    driver: bridge

volumes:
  db-data:
    driver: local

