version: '3.3'
services:
  db:
    container_name: ${APP_NAME}_db
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${HOST}:5432:${DB_PORT}
    networks:
      - skynet
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  skynet:
    external:
      name: skynet
