// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "studentgit.kata.academy/eazzyearn/students/mono/monolith/internal/models"

	utils "gitlab.com/golight/orm/utils"
)

// WebhookProcessHistorer is an autogenerated mock type for the WebhookProcessHistorer type
type WebhookProcessHistorer struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, dto
func (_m *WebhookProcessHistorer) Create(ctx context.Context, dto models.WebhookProcessHistoryDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.WebhookProcessHistoryDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, WebhookProcessHistoryID
func (_m *WebhookProcessHistorer) Delete(ctx context.Context, WebhookProcessHistoryID int) error {
	ret := _m.Called(ctx, WebhookProcessHistoryID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, WebhookProcessHistoryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, webhookProcessHistoryID
func (_m *WebhookProcessHistorer) GetByID(ctx context.Context, webhookProcessHistoryID int) (models.WebhookProcessHistoryDTO, error) {
	ret := _m.Called(ctx, webhookProcessHistoryID)

	var r0 models.WebhookProcessHistoryDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.WebhookProcessHistoryDTO, error)); ok {
		return rf(ctx, webhookProcessHistoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.WebhookProcessHistoryDTO); ok {
		r0 = rf(ctx, webhookProcessHistoryID)
	} else {
		r0 = ret.Get(0).(models.WebhookProcessHistoryDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, webhookProcessHistoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, condition
func (_m *WebhookProcessHistorer) GetList(ctx context.Context, condition utils.Condition) ([]models.WebhookProcessHistoryDTO, error) {
	ret := _m.Called(ctx, condition)

	var r0 []models.WebhookProcessHistoryDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, utils.Condition) ([]models.WebhookProcessHistoryDTO, error)); ok {
		return rf(ctx, condition)
	}
	if rf, ok := ret.Get(0).(func(context.Context, utils.Condition) []models.WebhookProcessHistoryDTO); ok {
		r0 = rf(ctx, condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WebhookProcessHistoryDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, utils.Condition) error); ok {
		r1 = rf(ctx, condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, dto
func (_m *WebhookProcessHistorer) Update(ctx context.Context, dto models.WebhookProcessHistoryDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.WebhookProcessHistoryDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWebhookProcessHistorer interface {
	mock.TestingT
	Cleanup(func())
}

// NewWebhookProcessHistorer creates a new instance of WebhookProcessHistorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWebhookProcessHistorer(t mockConstructorTestingTNewWebhookProcessHistorer) *WebhookProcessHistorer {
	mock := &WebhookProcessHistorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
