apiVersion: v1
kind: Service
metadata:
  name: tradeapi-service
spec:
  selector:
    app: tradeapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
