// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "studentgit.kata.academy/eazzyearn/students/mono/monolith/internal/models"
)

// ExchangeLister is an autogenerated mock type for the ExchangeLister type
type ExchangeLister struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, dto
func (_m *ExchangeLister) Create(ctx context.Context, dto models.ExchangeListDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ExchangeListDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, exchangeID
func (_m *ExchangeLister) Delete(ctx context.Context, exchangeID int) error {
	ret := _m.Called(ctx, exchangeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, exchangeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, exchangeID
func (_m *ExchangeLister) GetByID(ctx context.Context, exchangeID int) (models.ExchangeListDTO, error) {
	ret := _m.Called(ctx, exchangeID)

	var r0 models.ExchangeListDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.ExchangeListDTO, error)); ok {
		return rf(ctx, exchangeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.ExchangeListDTO); ok {
		r0 = rf(ctx, exchangeID)
	} else {
		r0 = ret.Get(0).(models.ExchangeListDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, exchangeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx
func (_m *ExchangeLister) GetList(ctx context.Context) ([]models.ExchangeListDTO, error) {
	ret := _m.Called(ctx)

	var r0 []models.ExchangeListDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.ExchangeListDTO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.ExchangeListDTO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ExchangeListDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, dto
func (_m *ExchangeLister) Update(ctx context.Context, dto models.ExchangeListDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ExchangeListDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewExchangeLister interface {
	mock.TestingT
	Cleanup(func())
}

// NewExchangeLister creates a new instance of ExchangeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExchangeLister(t mockConstructorTestingTNewExchangeLister) *ExchangeLister {
	mock := &ExchangeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
