// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "studentgit.kata.academy/eazzyearn/students/mono/monolith/internal/models"

	utils "gitlab.com/golight/orm/utils"
)

// ExchangeOrderLogger is an autogenerated mock type for the ExchangeOrderLogger type
type ExchangeOrderLogger struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, dto
func (_m *ExchangeOrderLogger) Create(ctx context.Context, dto models.ExchangeOrderLogDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ExchangeOrderLogDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, exchangeOrderLogDTOID
func (_m *ExchangeOrderLogger) Delete(ctx context.Context, exchangeOrderLogDTOID int) error {
	ret := _m.Called(ctx, exchangeOrderLogDTOID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, exchangeOrderLogDTOID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, exchangeID
func (_m *ExchangeOrderLogger) GetByID(ctx context.Context, exchangeID int) (models.ExchangeOrderLogDTO, error) {
	ret := _m.Called(ctx, exchangeID)

	var r0 models.ExchangeOrderLogDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.ExchangeOrderLogDTO, error)); ok {
		return rf(ctx, exchangeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.ExchangeOrderLogDTO); ok {
		r0 = rf(ctx, exchangeID)
	} else {
		r0 = ret.Get(0).(models.ExchangeOrderLogDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, exchangeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, condition
func (_m *ExchangeOrderLogger) GetList(ctx context.Context, condition utils.Condition) ([]models.ExchangeOrderLogDTO, error) {
	ret := _m.Called(ctx, condition)

	var r0 []models.ExchangeOrderLogDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, utils.Condition) ([]models.ExchangeOrderLogDTO, error)); ok {
		return rf(ctx, condition)
	}
	if rf, ok := ret.Get(0).(func(context.Context, utils.Condition) []models.ExchangeOrderLogDTO); ok {
		r0 = rf(ctx, condition)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ExchangeOrderLogDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, utils.Condition) error); ok {
		r1 = rf(ctx, condition)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, dto
func (_m *ExchangeOrderLogger) Update(ctx context.Context, dto models.ExchangeOrderLogDTO) error {
	ret := _m.Called(ctx, dto)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ExchangeOrderLogDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewExchangeOrderLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewExchangeOrderLogger creates a new instance of ExchangeOrderLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExchangeOrderLogger(t mockConstructorTestingTNewExchangeOrderLogger) *ExchangeOrderLogger {
	mock := &ExchangeOrderLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
